// ── bookmarked data ── (Notion taxonomy: 5 categories, ~12 subcategories each)
// Each site: url, title, label, cat, sub

var DATA = [
  { "url":"http://1linelayouts.glitch.me/", "title":"1-Line Layouts",
    "label":"1linelayouts.glitch.me", "cat":"Tools & Community", "sub":"Cascading Style Sheets" },
  { "url":"http://www.36daysoftype.com/", "title":"36 days of type",
    "label":"36daysoftype.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://a11yproject.com/checklist/", "title":"Accessibility Checklist",
    "label":"a11yproject.com", "cat":"Design References", "sub":"A11y and checklists" },
  { "url":"https://about.me/", "title":"about.me | your personal homepage",
    "label":"about.me", "cat":"Tools & Community", "sub":"Decks, Cards, Pages" },
  { "url":"https://www.abstrakt.design/", "title":"abstrakt.design",
    "label":"abstrakt.design", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://www.accessguide.io/", "title":"Homepage - Access Guide",
    "label":"accessguide.io", "cat":"Design References", "sub":"A11y and checklists" },
  { "url":"https://adplist.org/", "title":"ADPList",
    "label":"adplist.org", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"https://www.airconsole.com/", "title":"AirConsole",
    "label":"airconsole.com", "cat":"Tools & Community", "sub":"Make a game" },
  { "url":"https://albumcolors.com/", "title":"Album Colors Of The Year",
    "label":"albumcolors.com", "cat":"Design Resources", "sub":"Colors" },
    { "url":"https://riso.lfesp.me/", "title":"Riso",
    "label":"riso.lfesp.me", "cat":"Design Resources", "sub":"Colors" },
  
  { "url":"https://javier.xyz/cohesive-colors", "title":"Cohesive Colors",
    "label":"cohesive-colors", "cat":"Design Resources", "sub":"Colors" },
    { "url":"https://www.radix-ui.com/colors", "title":"Accessible colors for UI",
    "label":"radix-ui.com", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://allifontforchristmas.com/", "title":"All I Font for Christmas",
    "label":"allifontforchristmas.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://alpha.womp.com/", "title":"Womp 3D for all",
    "label":"alpha.womp.com", "cat":"Design Resources", "sub":"3D" },
  { "url":"https://app.diagrams.net/", "title":"Flowchart Maker & Online Diagram Software",
    "label":"app.diagrams.net", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://app.lucidchart.com/", "title":"Log In",
    "label":"app.lucidchart.com", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://app.streamlineicons.com/illustrations-multicolor", "title":"Streamline 3.0",
    "label":"app.streamlineicons.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://apps.npr.org/joy-generator/#story=menu&page=0", "title":"NPR Joy Generator",
    "label":"apps.npr.org", "cat":"Pass Time", "sub":"Cats, Poetry and Joy" },
  { "url":"https://arc.net/", "title":"Arc from The Browser Company",
    "label":"arc.net", "cat":"Tools & Community", "sub":"Notes, browsers" },
  { "url":"https://www.are.na/", "title":"Are.na",
    "label":"are.na", "cat":"Tools & Community", "sub":"Notes, browsers" },
  { "url":"https://www.arkives.club/", "title":"Arkives Club",
    "label":"arkives.club", "cat":"Pass Time", "sub":"Site of Sites" },
   { "url":"https://archive.org/", "title":"The Internet Archive",
    "label":"archive.org", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"https://www.artefactgroup.com/resources/the-tarot-cards-of-tech/", "title":"The Tarot Cards of Tech",
    "label":"artefactgroup.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://artofsymbols.com/", "title":"Art of Symbols",
    "label":"artofsymbols.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://www.artofthetitle.com/", "title":"Art of the Title",
    "label":"artofthetitle.com", "cat":"Pass Time", "sub":"Film things" },
  { "url":"https://www.artofvisualdesign.com/aesthetic-quiz", "title":"Design Constellation Quiz",
    "label":"artofvisualdesign.com/aesthetic-quiz", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://www.artofvisualdesign.com/fontguessr", "title":"fontguessr",
    "label":"artofvisualdesign.com/fontguessr", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"http://aspect.app", "title":"Aspect",
    "label":"aspect.app", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.audubon.org/bird-guide", "title":"Audubon Guide to North American Birds",
    "label":"audubon.org", "cat":"Pass Time", "sub":"Birds, Flowers" },
    { "url":"https://www.blrbloom.com/", "title":"Bangalore Blooms",
    "label":"blrbloom.com", "cat":"Pass Time", "sub":"Birds, Flowers" },
  { "url":"https://www.autodraw.com/", "title":"AutoDraw",
    "label":"autodraw.com", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  
  { "url":"https://www.awwwards.com/awwwards/collections/free-fonts/", "title":"Free Fonts",
    "label":"awwwards.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://www.bayareamade.us/", "title":"Bay Area Made",
    "label":"bayareamade.us", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://bearblog.dev/", "title":"Bear Blog",
    "label":"bearblog.dev", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://cntrl.site/", "title":"Design Outstanding Websites.",
    "label":"cntrl.site", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://benediktlehnert.github.io/omgwfh/", "title":"OMG I'm working remotely",
    "label":"benediktlehnert.github.io", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://berlintransitmap.de/", "title":"New Berlin rapid transit route map",
    "label":"berlintransitmap.de", "cat":"Design References", "sub":"Maps" },
  { "url":"https://www.bigtimer.net/?minutes=10&repeat=false", "title":"Big Timer",
    "label":"bigtimer.net", "cat":"Learn & Collaborate", "sub":"Timers" },
  { "url":"https://haikei.app/generators/", "title":"Haikei",
    "label":"haikei.app", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://www.blobmaker.app/", "title":"Blobmaker",
    "label":"blobmaker.app", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://blot.im/examples", "title":"Examples - Blot",
    "label":"blot.im", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.bludit.com/", "title":"Bludit - Flat-File CMS",
    "label":"bludit.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://blush.design/", "title":"Blush",
    "label":"blush.design", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://blush.design/collections/open-peeps/builder/0Plb5AsWr", "title":"Open Peeps",
    "label":"blush.design/collections/open-peeps", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://bongo.cat/", "title":"Bongo Cat",
    "label":"bongo.cat", "cat":"Pass Time", "sub":"Cats, Poetry and Joy" },
  { "url":"https://brandcolors.net/", "title":"BrandColors",
    "label":"brandcolors.net", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://brandmark.io/logo-rank/", "title":"Logo Rank",
    "label":"brandmark.io", "cat":"Design Resources", "sub":"Logo Lab" },
  { "url":"https://brutalistwebsites.com/", "title":"Brutalist Websites",
    "label":"brutalistwebsites.com", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"https://busysimulator.com/", "title":"Busy Simulator",
    "label":"busysimulator.com", "cat":"Pass Time", "sub":"Sounds" },
  { "url":"https://buttons.evrone.com/", "title":"UI Kids",
    "label":"buttons.evrone.com", "cat":"Design References", "sub":"Interface Tips and Spells" },
  { "url":"https://buymeonce.com/", "title":"BuyMeOnce",
    "label":"buymeonce.com", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://cantunsee.space/", "title":"Can't Unsee",
    "label":"cantunsee.space", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://www.canva.com/ai-image-generator/", "title":"Canva AI Image Generator",
    "label":"canva.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://cargo.site/", "title":"Cargo",
    "label":"cargo.site", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://carrd.co/build#profile", "title":"Carrd",
    "label":"carrd.co", "cat":"Tools & Community", "sub":"Decks, Cards, Pages" },
  { "url":"https://www.casestudy.club/case-studies", "title":"Case Study Club",
    "label":"casestudy.club", "cat":"Design References", "sub":"UX Case studies" },
  { "url":"https://catalogue.projectsbyif.com/", "title":"Data Patterns Catalogue",
    "label":"catalogue.projectsbyif.com", "cat":"Design References", "sub":"Interface Patterns" },
  { "url":"https://chat.openai.com/chat", "title":"ChatGPT",
    "label":"chat.openai.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://www.checklist.design/", "title":"Checklist Design",
    "label":"checklist.design", "cat":"Design References", "sub":"A11y and checklists" },
  { "url":"https://www.circulardesignguide.com/resources", "title":"Circular Design Guide",
    "label":"circulardesignguide.com", "cat":"Design References", "sub":"Sustainable design" },
  { "url":"https://claude.ai/", "title":"Claude",
    "label":"claude.ai", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://climatetechatlas.com/", "title":"Climate Tech Atlas",
    "label":"climatetechatlas.com", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://codeofdesign.org/", "title":"Code of Design",
    "label":"codeofdesign.org", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://colorleap.app/dates", "title":"Color Leap",
    "label":"colorleap.app", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://contractbook.com/templates", "title":"Contractbook Templates",
    "label":"contractbook.com", "cat":"Learn & Collaborate", "sub":"Contracts, Emails" },
  { "url":"https://coolors.co/", "title":"Coolors",
    "label":"coolors.co", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://www.cosmos.so/", "title":"Cosmos",
    "label":"cosmos.so", "cat":"Tools & Community", "sub":"Moodboards, wormholes" },
  { "url":"https://sublime.app/", "title":"Sublime",
    "label":"sublime.app", "cat":"Tools & Community", "sub":"Moodboards, wormholes" },
  { "url":"https://creativemornings.com/", "title":"CreativeMornings",
    "label":"creativemornings.com", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"https://www.daily.place/", "title":"daily.place",
    "label":"daily.place", "cat":"Learn & Collaborate", "sub":"Timers" },
  { "url":"https://datavizproject.com/", "title":"Data Viz Project",
    "label":"datavizproject.com", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://www.dayroselane.com/hydrants", "title":"The Hydrant Directory",
    "label":"dayroselane.com", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://ddc.dk/tools-and-methods/", "title":"DDC Tools and Methods",
    "label":"ddc.dk", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://deadsimplesites.com/", "title":"Dead Simple Sites",
    "label":"deadsimplesites.com", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"http://www.dear-data.com/theproject", "title":"Dear Data",
    "label":"dear-data.com", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://dear-new-york.com/#", "title":"Dear New York",
    "label":"dear-new-york.com", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://www.deathtothestockphoto.com/", "title":"Death to Stock",
    "label":"deathtothestockphoto.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://deck.gallery/", "title":"deck.gallery",
    "label":"deck.gallery", "cat":"Tools & Community", "sub":"Decks, Cards, Pages" },
  { "url":"https://designbooks.org/", "title":"Design Books",
    "label":"designbooks.org", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://designercize.com/", "title":"Designercize",
    "label":"designercize.com", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://www.designerslack.community/", "title":"Designer Slack Communities",
    "label":"designerslack.community", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"http://designishistory.com/", "title":"Design Is History",
    "label":"designishistory.com", "cat":"Design References", "sub":"Design Theory" },
  { "url":"https://www.designkit.org/", "title":"Design Kit",
    "label":"designkit.org", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://www.designspells.com/", "title":"Design Spells",
    "label":"designspells.com", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://www.designsystemchecklist.com/", "title":"Design System Checklist",
    "label":"designsystemchecklist.com", "cat":"Design References", "sub":"A11y and checklists" },
  { "url":"https://designtitles.com/", "title":"Design Titles",
    "label":"designtitles.com", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://www.are.na/leuys/a-collection-of-collections", "title":"Collection of Collections",
    "label":"a-collection-of-collections", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://diagram.website/", "title":"Diagram Website",
    "label":"diagram.website", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"https://digitalconfidence.design/", "title":"Designing for Digital Confidence",
    "label":"digitalconfidence.design", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://discord.gg/KvJbW74k", "title":"Design Buddies Discord",
    "label":"discord.gg", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"https://www.doc.cc/", "title":"DOC",
    "label":"doc.cc", "cat":"Design References", "sub":"Design Theory" },
  { "url":"https://docs.google.com/spreadsheets/d/16N5WYfoGiJfI496ybNYqQdgK0_hqoCuGcDRD2Kz00xE/edit#gid=1955919512", "title":"NN/g Customer Journey Mapping Template",
    "label":"docs.google.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://doteveryone.org.uk/project/consequence-scanning/", "title":"Consequence Scanning",
    "label":"doteveryone.org.uk", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
    { "url":"https://designtitles.com/", "title":"Design Titles",
    "label":"designtitles.com", "cat":"Pass Time", "sub":"typology, collections" },
      { "url":"https://felipe-hernandez.com/work/bar-napkin-archive", "title":"Bar Napkins",
    "label":"bar-napkin-archive", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://dropbox.design/resources", "title":"Dropbox Design Resources",
    "label":"dropbox.design", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://dscout.com/people-nerds", "title":"People Nerds by dscout",
    "label":"dscout.com", "cat":"Design References", "sub":"UX Case studies" },
  { "url":"https://duotone.shapefactory.co/", "title":"Duotone by ShapeFactory",
    "label":"duotone.shapefactory.co", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://www.eggradients.com/random-color-palette-generator", "title":"Random Color Palette Generator",
    "label":"eggradients.com", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://emaillove.com/inspiration/digital-product", "title":"Email Love",
    "label":"emaillove.com", "cat":"Learn & Collaborate", "sub":"Contracts, Emails" },
  { "url":"https://emilkowal.ski/ui/train-your-judgement", "title":"Train your judgement",
    "label":"emilkowal.ski/ui", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://www.etymologynerd.com/infographics.html", "title":"Etymology Infographics",
    "label":"etymologynerd.com", "cat":"Design References", "sub":"Maps" },
  { "url":"https://everynoise.com/engenremap.html", "title":"Every Noise at Once",
    "label":"everynoise.com", "cat":"Pass Time", "sub":"Sounds" },
  { "url":"https://experiments.withgoogle.com/ai/bird-sounds/view/", "title":"Bird Sounds",
    "label":"experiments.withgoogle.com", "cat":"Pass Time", "sub":"Birds, Flowers" },
  { "url":"https://eycndy.co/", "title":"Eyecandy",
    "label":"eycndy.co", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://faces.notion.com/", "title":"Notion Faces",
    "label":"faces.notion.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://farbvelo.elastiq.ch/", "title":"FarbVelo",
    "label":"farbvelo.elastiq.ch", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://felt.com/map", "title":"Felt",
    "label":"felt.com", "cat":"Design References", "sub":"Maps" },
  { "url":"https://www.figma.com/figjam/", "title":"FigJam",
    "label":"figma.com/figjam", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://www.figma.com/community/file/906159169146029844", "title":"Ikonate icons on Figma",
    "label":"figma.com/community/file", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://www.figma.com/community/search?query=mockup&resource_type=mixed&editor_type=all&price=all&sort_by=relevancy&creators=all", "title":"Figma mockups",
    "label":"figma.com/community/search", "cat":"Design Resources", "sub":"Mockups" },
  { "url":"https://www.figma.com/community/file/1197230942511819987/ecocards-jeu-de-cartes-decoconception-web-web-ecodesign-card-game", "title":"EcoCards",
    "label":"figma.com/community/ecocards", "cat":"Design References", "sub":"Sustainable design" },
  { "url":"https://findmy.vitra.com/en-en/questionnaire/chairs", "title":"Vitra Chair Finder",
    "label":"findmy.vitra.com", "cat":"Pass Time", "sub":"Test, Taste" },
  { "url":"https://fingerspelling.xyz/", "title":"Fingerspelling with ML",
    "label":"fingerspelling.xyz", "cat":"Learn & Collaborate", "sub":"sign language" },
  { "url":"https://firefly.adobe.com/", "title":"Adobe Firefly",
    "label":"firefly.adobe.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://www.flickr.com/photos/selfmagazine/albums/72157710332198661", "title":"SELF Vaccine Photo Project",
    "label":"flickr.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://flim.ai/", "title":"flim.ai",
    "label":"flim.ai", "cat":"Pass Time", "sub":"Film things" },
  { "url":"https://www.flowmapp.com/", "title":"FlowMapp",
    "label":"flowmapp.com", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://fontjoy.com/", "title":"Fontjoy",
    "label":"fontjoy.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://fontofthemonth.club/", "title":"Font of the Month Club",
    "label":"fontofthemonth.club", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://fonts.google.com/", "title":"Google Fonts",
    "label":"fonts.google.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://www.fontshare.com/pairs", "title":"Fontshare",
    "label":"fontshare.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://fontsinuse.com/", "title":"Fonts In Use",
    "label":"fontsinuse.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://foresight.unglobalpulse.net/how-tools/", "title":"UNGP Foresight Tools",
    "label":"foresight.unglobalpulse.net", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://www.format.com", "title":"Format",
    "label":"format.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://foundcolor.co/archive", "title":"Found Color Archive",
    "label":"foundcolor.co", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://fruitsof.work/viewdata/table", "title":"Fruits of Work",
    "label":"fruitsof.work", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"https://www.futurematerialsbank.com/materials/", "title":"Future Materials Bank",
    "label":"futurematerialsbank.com", "cat":"Design References", "sub":"Sustainable design" },
  { "url":"https://gamma.app/", "title":"Gamma",
    "label":"gamma.app", "cat":"Tools & Community", "sub":"Decks, Cards, Pages" },
  { "url":"https://www.gather.town/", "title":"Gather",
    "label":"gather.town", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://gatheround.com/", "title":"Gatheround",
    "label":"gatheround.com", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://getavataaars.com/", "title":"Avataaars Generator",
    "label":"getavataaars.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://www.glyphy.io/", "title":"Glyphy",
    "label":"glyphy.io", "cat":"Design Resources", "sub":"Glyphs and Patterns" },
  { "url":"https://www.gov.uk/guidance/government-design-principles#start-with-user-needs", "title":"Government Design Principles",
    "label":"gov.uk", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://grabient.com/", "title":"Grabient",
    "label":"grabient.com", "cat":"Tools & Community", "sub":"Cascading Style Sheets" },
  { "url":"http://gradient.horse/", "title":"gradient.horse",
    "label":"gradient.horse", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  
  { "url":"https://www.photopea.com/", "title":"Photoshop Online",
    "label":"photopea.com", "cat":"Tools & Community", "sub":"Alternate Tools" },
    { "url":"https://www.remove.bg/", "title":"Remove Background",
    "label":"remove.bg", "cat":"Tools & Community", "sub":"Alternate Tools" },
    { "url":" https://alternativeto.net/", "title":"Crowdsourced Alternate Tools",
    "label":"alternativeto.net", "cat":"Tools & Community", "sub":"Alternate Tools" },
 
  { "url":"https://graphicburger.com/", "title":"GraphicBurger",
    "label":"graphicburger.com", "cat":"Design Resources", "sub":"Mockups" },
  { "url":"http://grid.guide/", "title":"grid.guide",
    "label":"grid.guide", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://gridbyexample.com/examples/", "title":"Grid by Example",
    "label":"gridbyexample.com", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://grids.obys.agency/", "title":"Grids by Obys",
    "label":"grids.obys.agency", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://growth.design/case-studies/", "title":"Growth.Design Case Studies",
    "label":"growth.design", "cat":"Design References", "sub":"UX Case studies" },
  { "url":"https://guide.onym.co/", "title":"Onym",
    "label":"guide.onym.co", "cat":"Design References", "sub":"Naming Guide" },
  { "url":"https://www.happyhues.co/", "title":"Happy Hues",
    "label":"happyhues.co", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://www.historicaltechtree.com/", "title":"Historical Tech Tree",
    "label":"historicaltechtree.com", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"http://honeylux.com/project/how-we-describe-books/", "title":"How We Describe Books",
    "label":"honeylux.com", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://hoodmaps.com/", "title":"Hoodmaps",
    "label":"hoodmaps.com", "cat":"Design References", "sub":"Maps" },
  { "url":"https://www.horg.com/horg/", "title":"Holotypic Occlupanid Research Group",
    "label":"horg.com", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://housesof.world/", "title":"Houses Of The World",
    "label":"housesof.world", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://syzygy.theneighborhoods.nyc", "title":"Twin Houses",
    "label":"syzygy.theneighborhoods.nyc", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://housesof.world/location/australia/brisbane", "title":"Houses Of Brisbane",
    "label":"housesof.world/location/australia", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"http://housesofgoa.com/", "title":"Houses of Goa",
    "label":"housesofgoa.com", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"http://howbigismybrowser.com/", "title":"How Big Is My Browser?",
    "label":"howbigismybrowser.com", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://www.hubspot.com/make-my-persona", "title":"HubSpot Make My Persona",
    "label":"hubspot.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://humanebydesign.com/principles", "title":"Humane by Design",
    "label":"humanebydesign.com", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://www.ibm.com/design/thinking/page/toolkit", "title":"IBM Design Thinking Toolkit",
    "label":"ibm.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://icebreakerz.vercel.app/", "title":"Icebreakerz",
    "label":"icebreakerz.vercel.app", "cat":"Learn & Collaborate", "sub":"IceBreakers" },
  { "url":"https://icons8.com/", "title":"Icons8",
    "label":"icons8.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://icons8.com/mega-creator/dashboard", "title":"Mega Creator by Icons8",
    "label":"icons8.com/mega-creator", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://icons8.com/ouch", "title":"Ouch by Icons8",
    "label":"icons8.com/ouch", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://iconscout.com/unicons", "title":"Unicons by Iconscout",
    "label":"iconscout.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://imgbin.com/", "title":"IMGBIN",
    "label":"imgbin.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://imisstheoffice.eu/", "title":"I Miss the Office",
    "label":"imisstheoffice.eu", "cat":"Pass Time", "sub":"Sounds" },
  { "url":"https://www.indiantypefoundry.com/", "title":"Indian Type Foundry",
    "label":"indiantypefoundry.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://info2.frogdesign.com/en/collective-action-toolkit?_ga=2.252573697.967779647.1589670252-1934228244.1587431214", "title":"Collective Action Toolkit",
    "label":"info2.frogdesign.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://informationart.com/", "title":"Information Art",
    "label":"informationart.com", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://informationisbeautiful.net/", "title":"Information is Beautiful",
    "label":"informationisbeautiful.net", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://ingradients.net/", "title":"Ingradients",
    "label":"ingradients.net", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://www.instagram.com/cvrlvr?igsh=MmVlMjlkMTBhMg==&utm_source=qr", "title":"Instagram (@cvrlvr)",
    "label":"instagram.com/cvrlvr", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://www.instagram.com/housesofberkeley/", "title":"Houses of Berkeley on Instagram",
    "label":"instagram.com/housesofberkeley", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://internetphonebook.net/dial/", "title":"Internet Phone Book",
    "label":"internetphonebook.net", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"https://www.iosicongallery.com/", "title":"iOS Icon Gallery",
    "label":"iosicongallery.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://jaali.indiansummerfest.ca/", "title":"JAALI",
    "label":"jaali.indiansummerfest.ca", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://javier.xyz/emoji-to-scale/", "title":"Emoji to Scale",
    "label":"javier.xyz", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://jonsuh.com/hamburgers/", "title":"Hamburgers",
    "label":"jonsuh.com", "cat":"Tools & Community", "sub":"Cascading Style Sheets" },
  { "url":"https://jxnblk.github.io/hello-color/?c=e78664", "title":"Hello Color",
    "label":"jxnblk.github.io", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://killedbygoogle.com/", "title":"Killed by Google",
    "label":"killedbygoogle.com", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"https://kinopio.club/", "title":"Kinopio",
    "label":"kinopio.club", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://www.kosmik.app/", "title":"Kosmik",
    "label":"kosmik.app", "cat":"Tools & Community", "sub":"Notes, browsers" },
  { "url":"https://ladieswinedesign.com/", "title":"Ladies, Wine & Design",
    "label":"ladieswinedesign.com", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"http://lawsofux.com/", "title":"Laws of UX",
    "label":"lawsofux.com", "cat":"Design References", "sub":"UX Methods, Laws" },
  { "url":"https://layers.to/explore", "title":"Layers",
    "label":"layers.to/explore", "cat":"Design References", "sub":"Interface Patterns" },
  { "url":"https://leaflet.pub/home", "title":"Leaflet",
    "label":"leaflet.pub", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://leroyalmeida.github.io/special-projects/uncommon-library/", "title":"Uncommon Library",
    "label":"leroyalmeida.github.io", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://letterboxd.com/", "title":"Letterboxd",
    "label":"letterboxd.com", "cat":"Pass Time", "sub":"Film things" },
  { "url":"https://lifecentereddesign.net/resources", "title":"Life Centered Design",
    "label":"lifecentereddesign.net", "cat":"Design References", "sub":"Sustainable design" },
  { "url":"https://www.linkbouquet.com/", "title":"Link Bouquet",
    "label":"linkbouquet.com", "cat":"Pass Time", "sub":"Birds, Flowers" },
  { "url":"https://literal.club/", "title":"Literal",
    "label":"literal.club", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://logo.pizza/", "title":"Logo Pizza",
    "label":"logo.pizza", "cat":"Design Resources", "sub":"Logo Lab" },
  { "url":"https://logolab.app/home", "title":"Logo Lab",
    "label":"logolab.app", "cat":"Design Resources", "sub":"Logo Lab" },
  { "url":"https://looka.com/", "title":"Looka",
    "label":"looka.com", "cat":"Design Resources", "sub":"Logo Lab" },
  { "url":"https://lorem.space/", "title":"Lorem.space",
    "label":"lorem.space", "cat":"Design Resources", "sub":"Mockups" },
  { "url":"https://www.losttype.com/", "title":"Lost Type Co-op",
    "label":"losttype.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://lottiefiles.com/recent", "title":"LottieFiles",
    "label":"lottiefiles.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://lu.ma/home", "title":"Luma",
    "label":"lu.ma", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"https://www.lummi.ai/", "title":"Lummi",
    "label":"lummi.ai", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://www.macosicongallery.com/", "title":"macOS Icon Gallery",
    "label":"macosicongallery.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://www.magicpattern.design/tools/css-backgrounds", "title":"CSS Background Patterns",
    "label":"magicpattern.design", "cat":"Design Resources", "sub":"Glyphs and Patterns" },
  { "url":"https://www.mazegenerator.net/", "title":"Maze Generator",
    "label":"mazegenerator.net", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://www.mcmaster.com/", "title":"McMaster-Carr",
    "label":"mcmaster.com", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://medium.muz.li/10-links-to-create-a-design-concept-3d-part-one-2563d6d50a39", "title":"10 Links To Create a Design Concept 3D",
    "label":"medium.muz.li", "cat":"Design Resources", "sub":"3D" },
  { "url":"https://www.microsoft.com/design/inclusive/", "title":"Microsoft Inclusive Design",
    "label":"microsoft.com", "cat":"Design References", "sub":"A11y and checklists" },
  { "url":"https://www.midjourney.com/showcase", "title":"Midjourney",
    "label":"midjourney.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://mindfuldesigntechnologist.xyz/", "title":"Mindful Design Technologist",
    "label":"mindfuldesigntechnologist.xyz", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://minimator.maxwellito.com/", "title":"Minimator",
    "label":"minimator.app", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  { "url":"https://miro.com/", "title":"Miro",
    "label":"miro.com", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://miro.com/app/board/o9J_ktZHnRA=/", "title":"UX Design Methods on Miro",
    "label":"miro.com/app/board", "cat":"Design References", "sub":"UX Methods, Laws" },
  { "url":"https://www.misha.studio/snowflaker/", "title":"Snowflaker",
    "label":"misha.studio", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://www.mixamo.com/#/", "title":"Mixamo",
    "label":"mixamo.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://mixkit.co/free-stock-art/", "title":"Mixkit Free Stock Art",
    "label":"mixkit.co", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://www.moodboardcreator.dev/", "title":"Moodboard Creator",
    "label":"moodboardcreator.dev", "cat":"Tools & Community", "sub":"Moodboards, wormholes" },
  { "url":"https://mrmockup.com/freebies/", "title":"Mr.Mockup Freebies",
    "label":"mrmockup.com", "cat":"Design Resources", "sub":"Mockups" },
  { "url":"https://museumhack.com/list-icebreakers-questions/#virtual", "title":"Icebreaker Questions",
    "label":"museumhack.com", "cat":"Learn & Collaborate", "sub":"IceBreakers" },
  { "url":"https://mycreativetype.com/", "title":"Creative Types by Adobe",
    "label":"mycreativetype.com", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://mymind.com/", "title":"mymind",
    "label":"mymind.com", "cat":"Tools & Community", "sub":"Notes, browsers" },
  { "url":"https://mythopedia.com/", "title":"Mythopedia",
    "label":"mythopedia.com", "cat":"Pass Time", "sub":"Mythology" },
  { "url":"https://nachhaltiges-webdesign.jetzt/", "title":"Sustainable Web Design",
    "label":"nachhaltiges-webdesign.jetzt", "cat":"Design References", "sub":"Sustainable design" },
  { "url":"https://neocities.org/", "title":"Neocities",
    "label":"neocities.org", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://neumorphic.design/", "title":"Neumorphic Generator",
    "label":"neumorphic.design", "cat":"Tools & Community", "sub":"Cascading Style Sheets" },
  { "url":"https://www.newrafael.com/internet/", "title":"Internet by Rafael Rozendaal",
    "label":"newrafael.com", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://www.nfb.ca/film/how-to-be-at-home/", "title":"How To Be At Home",
    "label":"nfb.ca", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://www.nngroup.com/articles/ten-usability-heuristics/", "title":"10 Usability Heuristics",
    "label":"nngroup.com", "cat":"Design References", "sub":"UX Methods, Laws" },
  { "url":"https://now.page/", "title":"now.",
    "label":"now.page", "cat":"Tools & Community", "sub":"Decks, Cards, Pages" },
  { "url":"https://www.nytimes.com/interactive/2021/04/02/arts/design/shah-jahan-chitarman.html", "title":"What a Tiny Masterpiece Reveals About Power and Beauty",
    "label":"nytimes.com", "cat":"Learn & Collaborate", "sub":"A lesson in Art History" },
  { "url":"https://obsidian.md/", "title":"Obsidian",
    "label":"obsidian.md", "cat":"Tools & Community", "sub":"Notes, browsers" },
  { "url":"https://octopus.do/", "title":"Octopus.do",
    "label":"octopus.do", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://www.oldmapsonline.org/", "title":"Old Maps Online",
    "label":"oldmapsonline.org", "cat":"Design References", "sub":"Maps" },
  { "url":"https://onthegrid.city/#cities", "title":"On the Grid",
    "label":"onthegrid.city", "cat":"Tools & Community", "sub":"local" },
  { "url":"https://openai.com/dall-e-2", "title":"DALL-E 2",
    "label":"openai.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://optimism.museum/", "title":"Museum of Optimism",
    "label":"optimism.museum", "cat":"Pass Time", "sub":"Cats, Poetry and Joy" },
  { "url":"http://ourownthing.co.uk/gradpad.html", "title":"GradPad",
    "label":"ourownthing.co.uk", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://pageflows.com/ios/", "title":"Page Flows",
    "label":"pageflows.com", "cat":"Design References", "sub":"Interface Patterns" },
    { "url":"https://refero.design/", "title":"Design Research and References",
    "label":"refero.design", "cat":"Design References", "sub":"Interface Patterns" },
  
  { "url":"https://papersizes.io/", "title":"Paper Sizes",
    "label":"papersizes.io", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://patternclub.io/", "title":"Pattern Club",
    "label":"patternclub.io", "cat":"Design Resources", "sub":"Glyphs and Patterns" },
  { "url":"https://www.peculiarmanicule.com/", "title":"The Peculiar Manicule",
    "label":"peculiarmanicule.com", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://peeps.ui8.net/", "title":"Peeps Avatar Builder",
    "label":"peeps.ui8.net", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://pelacase.com/pages/the-biodegradable-phone-case-vs-a-billion-dollar-industry", "title":"Pela Case",
    "label":"pelacase.com", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://www.pexels.com/", "title":"Pexels",
    "label":"pexels.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://pigment.shapefactory.co/", "title":"Pigment by ShapeFactory",
    "label":"pigment.shapefactory.co", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://pika.page/", "title":"Pika",
    "label":"pika.page", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.piliapp.com/actual-size/inch-ruler/", "title":"Actual Size Inch Ruler",
    "label":"piliapp.com", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://www.pinterest.com/", "title":"Pinterest",
    "label":"pinterest.com", "cat":"Tools & Community", "sub":"Moodboards, wormholes" },
  { "url":"https://www.pitchdeckhunt.com/", "title":"Pitch Deck Hunt",
    "label":"pitchdeckhunt.com", "cat":"Tools & Community", "sub":"Decks, Cards, Pages" },
  { "url":"https://pixelcraft.web.app/", "title":"PixelCraft",
    "label":"pixelcraft.web.app", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  { "url":"https://www.pixpa.com/", "title":"Pixpa",
    "label":"pixpa.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.placestoread.xyz/", "title":"Places to Read",
    "label":"placestoread.xyz", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"http://playingcards.io/", "title":"PlayingCards.io",
    "label":"playingcards.io", "cat":"Tools & Community", "sub":"Make a game" },
  { "url":"https://www.playphrase.me/", "title":"PlayPhrase.me",
    "label":"playphrase.me", "cat":"Pass Time", "sub":"Film things" },
  { "url":"https://podcastmagic.app/", "title":"Podcast Magic",
    "label":"podcastmagic.app", "cat":"Tools & Community", "sub":"miscellaneous" },
  { "url":"https://lightpage.com/", "title":"Notebook that talks back",
    "label":"lightpage.com", "cat":"Tools & Community", "sub":"Notes, browsers" },
  { "url":"https://www.precyclenyc.com/", "title":"Precycle",
    "label":"precyclenyc.com", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://principles.design/", "title":"Design Principles",
    "label":"principles.design", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://productplacementblog.com/", "title":"Product Placement Blog",
    "label":"productplacementblog.com", "cat":"Pass Time", "sub":"Film things" },
  { "url":"https://products.ls.graphics/mesh-gradients/", "title":"Free Mesh Gradient Collection",
    "label":"products.ls.graphics", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://projectturntable.webflow.io/#", "title":"Project Turntable",
    "label":"projectturntable.webflow.io", "cat":"Pass Time", "sub":"TV, Radio" },
  { "url":"https://public.work/", "title":"Public Work by Cosmos",
    "label":"public.work", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://pudding.cool/", "title":"The Pudding",
    "label":"pudding.cool", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://qodeinteractive.com/magazine/interactive-maps-in-web-design/", "title":"Interactive Maps in Web Design",
    "label":"qodeinteractive.com", "cat":"Design References", "sub":"Maps" },
  { "url":"https://quickdraw.withgoogle.com/", "title":"Quick, Draw!",
    "label":"quickdraw.withgoogle.com", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  { "url":"http://quiz.creativeladder.org/", "title":"Career Finder Quiz",
    "label":"quiz.creativeladder.org", "cat":"Pass Time", "sub":"Test, Taste" },
  { "url":"http://radio.garden/", "title":"Radio Garden",
    "label":"radio.garden", "cat":"Pass Time", "sub":"TV, Radio" },
  { "url":"https://radiooooo.com/", "title":"Radiooooo",
    "label":"radiooooo.com", "cat":"Pass Time", "sub":"TV, Radio" },
  { "url":"https://readymag.com/", "title":"Readymag",
    "label":"readymag.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.rebrand.gallery/bentos", "title":"Rebrand Gallery",
    "label":"rebrand.gallery", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://www.reginald.co/", "title":"Reginald",
    "label":"reginald.co", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"http://www.responsivelogos.co.uk/", "title":"Responsive Logos",
    "label":"responsivelogos.co.uk", "cat":"Design Resources", "sub":"Logo Lab" },
  { "url":"https://www.shapes.gallery/", "title":"Copy-Paste SVG Shapes",
    "label":"shapes.gallery", "cat":"Design Resources", "sub":"Glyphs and Patterns" },
  { "url":"https://savee.it/", "title":"SAVEE",
    "label":"savee.it", "cat":"Tools & Community", "sub":"Moodboards, wormholes" },
  { "url":"http://savethesounds.info/", "title":"Museum of Endangered Sounds",
    "label":"savethesounds.info", "cat":"Pass Time", "sub":"Sounds" },
  { "url":"https://scaleofuniverse.com/", "title":"Scale of the Universe",
    "label":"scaleofuniverse.com", "cat":"Design Resources", "sub":"Scales and Grids" },
  { "url":"https://science.nasa.gov/specials/your-name-in-landsat", "title":"Your Name in Landsat",
    "label":"science.nasa.gov", "cat":"Pass Time", "sub":"Earth Typo" },
  { "url":"https://www.semplice.com/", "title":"Semplice",
    "label":"semplice.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.sensiblefutures.co/", "title":"Sensible Futures",
    "label":"sensiblefutures.co", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://servicedesigntools.org/enhanced-tools", "title":"Service Design Tools",
    "label":"servicedesigntools.org", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://shailendra.me/kolam/", "title":"Kolam",
    "label":"shailendra.me", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://www.shapedivider.app/", "title":"Custom Shape Dividers",
    "label":"shapedivider.app", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://shelby.cool/field-of-flowers/", "title":"field of flowers",
    "label":"shelby.cool/field-of-flowers", "cat":"Pass Time", "sub":"Birds, Flowers" },
  { "url":"https://shelby.cool/a-room-with-a-window/", "title":"A Room with a Window",
    "label":"shelby.cool/a-room-with-a-window", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://www.shortoftheweek.com/", "title":"Short of the Week",
    "label":"shortoftheweek.com", "cat":"Pass Time", "sub":"Film things" },
  { "url":"https://signfree.io/", "title":"SignFree",
    "label":"signfree.io", "cat":"Learn & Collaborate", "sub":"Contracts, Emails" },
  { "url":"https://www.signs.com/branded-in-memory/#starbucks", "title":"Branded in Memory",
    "label":"signs.com", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  { "url":"https://sinceyouarrived.world/taken", "title":"Since You Arrived",
    "label":"sinceyouarrived.world", "cat":"Tools & Community", "sub":"Cookies" },
  { "url":"https://www.siteofsites.co/", "title":"Site of Sites",
    "label":"siteofsites.co", "cat":"Pass Time", "sub":"Site of Sites" },
  { "url":"https://sites.elliott.computer/one-minute-park/", "title":"One Minute Park",
    "label":"sites.elliott.computer", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://sixfeetapartplease.com/", "title":"Six Feet Apart",
    "label":"sixfeetapartplease.com", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://www.sketchplanations.com/", "title":"Sketchplanations",
    "label":"sketchplanations.com", "cat":"Learn & Collaborate", "sub":"Sketchplanations" },
  { "url":"https://snorpey.github.io/jpg-glitch/", "title":"Image Glitch Tool",
    "label":"snorpey.github.io", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://societycentered.design/", "title":"Society Centered Design",
    "label":"societycentered.design", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://www.sofarsounds.com/", "title":"Sofar Sounds",
    "label":"sofarsounds.com", "cat":"Tools & Community", "sub":"local" },
  { "url":"https://www.springimpact.org/toolkit-home/", "title":"Scaling Impact Toolkit",
    "label":"springimpact.org", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://sprout.place/", "title":"Sprout",
    "label":"sprout.place", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://sprrrint.com/whats-new", "title":"Sprrrint",
    "label":"sprrrint.com", "cat":"Design References", "sub":"Interface Patterns" },
  { "url":"https://www.squarespace.com/", "title":"Squarespace",
    "label":"squarespace.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://start.mural.co/", "title":"Mural",
    "label":"start.mural.co", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://start.uxdesign.cc/", "title":"The Guide to Design",
    "label":"start.uxdesign.cc", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://stompy-staging.mybigcommerce.com/quiz/", "title":"Stompy Quiz",
    "label":"stompy-staging.mybigcommerce.com", "cat":"Pass Time", "sub":"Test, Taste" },
  { "url":"https://stories.maker.co/", "title":"Maker Stories",
    "label":"stories.maker.co", "cat":"Design References", "sub":"Design Theory" },
  { "url":"https://storyset.com/", "title":"Storyset",
    "label":"storyset.com", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://sustainableuxmanifesto.com/", "title":"Sustainable UX Manifesto",
    "label":"sustainableuxmanifesto.com", "cat":"Design References", "sub":"Sustainable design" },
  { "url":"https://www.svgbackgrounds.com/", "title":"SVG Backgrounds",
    "label":"svgbackgrounds.com", "cat":"Tools & Community", "sub":"Cascading Style Sheets" },
  { "url":"https://symbl.cc/en/", "title":"SYMBL",
    "label":"symbl.cc", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://tablericons.com/", "title":"Tabler Icons",
    "label":"tablericons.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://thebreakfast.app/", "title":"The Breakfast App",
    "label":"thebreakfast.app", "cat":"Tools & Community", "sub":"local" },
  { "url":"https://thecrashcourse.com/topic/mythology/", "title":"Crash Course Mythology",
    "label":"thecrashcourse.com", "cat":"Pass Time", "sub":"Mythology" },
  { "url":"https://themockup.club/", "title":"The Mockup Club",
    "label":"themockup.club", "cat":"Design Resources", "sub":"Mockups" },
  { "url":"http://thenostalgiamachine.com/y/#2008", "title":"The Nostalgia Machine",
    "label":"thenostalgiamachine.com", "cat":"Pass Time", "sub":"TV, Radio" },
  { "url":"https://thenounproject.com/", "title":"Noun Project",
    "label":"thenounproject.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"http://thepoliticsofdesign.com/", "title":"The Politics of Design",
    "label":"thepoliticsofdesign.com", "cat":"Design References", "sub":"Design Theory" },
  { "url":"https://thewallyshop.co/", "title":"The Wally Shop",
    "label":"thewallyshop.co", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://www.thisisservicedesigndoing.com/methods", "title":"This is Service Design Doing",
    "label":"thisisservicedesigndoing.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://thispersondoesnotexist.com/", "title":"This Person Does Not Exist",
    "label":"thispersondoesnotexist.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://thisxdoesnotexist.com/", "title":"This X Does Not Exist",
    "label":"thisxdoesnotexist.com", "cat":"Design Resources", "sub":"Personas and Journey Maps" },
  { "url":"https://timezen.com/", "title":"TimeZen",
    "label":"timezen.com", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://www.timezoneglobe.com/", "title":"Timezone Globe",
    "label":"timezoneglobe.com", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://tinkersynth.com/slopes/", "title":"Generative Art Machine",
    "label":"tinkersynth.com", "cat":"Tools & Community", "sub":"Generators" },
  { "url":"https://www.tldraw.com/", "title":"tldraw",
    "label":"tldraw.com", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://toolbox.hyperisland.com/", "title":"Hyper Island Toolbox",
    "label":"toolbox.hyperisland.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://toolkit.ttclabs.net/", "title":"TTC Labs Toolkit",
    "label":"toolkit.ttclabs.net", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://www.tooooools.app/", "title":"Tooooools.app",
    "label":"tooooools.app", "cat":"Tools & Community", "sub":"miscellaneous" },
    { "url":"https://everywhere.tools/", "title":"open source tools for designers",
    "label":"everywhere.tools", "cat":"Tools & Community", "sub":"miscellaneous" },
  { "url":"https://www.traveloka.com/special/urban-scrawl", "title":"Urban Scrawl",
    "label":"traveloka.com", "cat":"Tools & Community", "sub":"Drawing, Scrawling" },
  { "url":"https://www.trendlist.org/", "title":"Trend List",
    "label":"trendlist.org", "cat":"Design References", "sub":"eyecandy" },
  { "url":"https://www.try.vi/wine", "title":"Vi Wine Explorer",
    "label":"try.vi", "cat":"Pass Time", "sub":"Test, Taste" },
  { "url":"https://www.tumblr.com/", "title":"Tumblr",
    "label":"tumblr.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.typewolf.com/", "title":"Typewolf",
    "label":"typewolf.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://www.typography.com/", "title":"Hoefler & Co.",
    "label":"typography.com", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://www.uibot.app/", "title":"Uibot",
    "label":"uibot.app", "cat":"Design References", "sub":"Interface Patterns" },
  { "url":"https://www.uidesign.tips/ux-tips", "title":"UX Tips by Jim Raptis",
    "label":"uidesign.tips", "cat":"Design References", "sub":"Interface Tips and Spells" },
  { "url":"https://uiplaybook.dev/", "title":"UI Playbook",
    "label":"uiplaybook.dev", "cat":"Design References", "sub":"Interface Patterns" },
  { "url":"https://buildui.com/", "title":"UI Recipes",
    "label":"buildui.com", "cat":"Design References", "sub":"Interface Tips and Spells" },
  { "url":"https://universaldesignguide.com/universal-design/", "title":"Universal Design",
    "label":"universaldesignguide.com/universal-design", "cat":"Design References", "sub":"Guides, Codes, Manifestos" },
  { "url":"https://universaldesignguide.com/", "title":"Universal Design Guide",
    "label":"universaldesignguide.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://unsplash.com/images", "title":"Unsplash",
    "label":"unsplash.com", "cat":"Design Resources", "sub":"Image Generation" },
  { "url":"https://untools.co/", "title":"Untools",
    "label":"untools.co", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://upload.wikimedia.org/wikipedia/commons/6/65/Cognitive_bias_codex_en.svg", "title":"Cognitive Bias Codex",
    "label":"upload.wikimedia.org", "cat":"Learn & Collaborate", "sub":"Cognitive Bias Index" },
  { "url":"https://useless.london/kit", "title":"USELESS",
    "label":"useless.london", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://userinyerface.com/", "title":"User Inyerface",
    "label":"userinyerface.com", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://www.useronboard.com/onboarding-ux-patterns/", "title":"User Onboarding Patterns",
    "label":"useronboard.com", "cat":"Design References", "sub":"Interface Patterns" },
  { "url":"https://uxtools.co/challenges/", "title":"UX Design Challenges",
    "label":"uxtools.co", "cat":"Design Resources", "sub":"Exercise, Quizzes" },
  { "url":"https://vanschneider.com/colors", "title":"Colors by Van Schneider",
    "label":"vanschneider.com", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://vignellicenter.tumblr.com/", "title":"Vignelli Center Archive",
    "label":"vignellicenter.tumblr.com", "cat":"Design References", "sub":"Design Theory" },
  { "url":"https://www.virsa.info/bhangralexicon/", "title":"Bhangra Lexicon",
    "label":"virsa.info", "cat":"Pass Time", "sub":"typology, collections" },
  { "url":"https://www.visualcapitalist.com/", "title":"Visual Capitalist",
    "label":"visualcapitalist.com", "cat":"Design References", "sub":"Data Visualized" },
  { "url":"https://wastebased.co/", "title":"Wastebased",
    "label":"wastebased.co", "cat":"Learn & Collaborate", "sub":"Zero Waste Resources" },
  { "url":"https://www.watchosicongallery.com/", "title":"watchOS Icon Gallery",
    "label":"watchosicongallery.com", "cat":"Design Resources", "sub":"Icons & Symbology" },
  { "url":"https://weareskribbl.com/", "title":"Skribbl",
    "label":"weareskribbl.com", "cat":"Design Resources", "sub":"Illustrations" },
  { "url":"https://webaccessibilitychecklist.com/", "title":"Web Accessibility Checklist",
    "label":"webaccessibilitychecklist.com", "cat":"Design References", "sub":"A11y and checklists" },
    { "url":"https://abc.useallfive.com/?colors", "title":"Accessible Brand Colors",
    "label":"abc.useallfive.com", "cat":"Design References", "sub":"A11y and checklists" },
  { "url":"https://webaim.org/resources/contrastchecker/", "title":"Contrast Checker",
    "label":"webaim.org", "cat":"Design Resources", "sub":"Colors" },
  { "url":"https://webflow.com/", "title":"Webflow",
    "label":"webflow.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://www.websitecarbon.com/", "title":"Website Carbon Calculator",
    "label":"websitecarbon.com", "cat":"Pass Time", "sub":"Test, Taste" },
  { "url":"https://whimsical.com/", "title":"Whimsical",
    "label":"whimsical.com", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://whocares.bigbump.fr/", "title":"Who Cares?",
    "label":"whocares.bigbump.fr", "cat":"Learn & Collaborate", "sub":"Endangered" },
  { "url":"https://window-swap.com/", "title":"WindowSwap",
    "label":"window-swap.com", "cat":"Pass Time", "sub":"Windows, Houses, Parks" },
  { "url":"https://witeboard.com/", "title":"Witeboard",
    "label":"witeboard.com", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://www.wix.com/", "title":"Wix",
    "label":"wix.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://womenwho.design/", "title":"Women Who Design",
    "label":"womenwho.design", "cat":"Tools & Community", "sub":"design communities" },
  { "url":"https://wordmark.it/", "title":"Wordmark.it",
    "label":"wordmark.it", "cat":"Design Resources", "sub":"Typography" },
  { "url":"https://wordpress.com/", "title":"WordPress",
    "label":"wordpress.com", "cat":"Tools & Community", "sub":"Publish a website, blog" },
  { "url":"https://wordwebs.app/home", "title":"Word Webs",
    "label":"wordwebs.app", "cat":"Design Resources", "sub":"Boards, Charts, Mind maps" },
  { "url":"https://writingexamples.com/", "title":"Writing Examples",
    "label":"writingexamples.com", "cat":"Pass Time", "sub":"Books, Places to read" },
  { "url":"https://xplane.com/worksheets/", "title":"XPLANE Worksheets",
    "label":"xplane.com", "cat":"Tools & Community", "sub":"Toolkits + Method Cards" },
  { "url":"https://yourbias.is/", "title":"Your Bias Is",
    "label":"yourbias.is", "cat":"Learn & Collaborate", "sub":"Cognitive Bias Index" },
  { "url":"https://ytch.xyz/", "title":"YTCH",
    "label":"ytch.xyz", "cat":"Pass Time", "sub":"TV, Radio" },
  { "url":"https://zoomescaper.com/", "title":"Zoom Escaper",
    "label":"zoomescaper.com", "cat":"Learn & Collaborate", "sub":"Work from anywhere" },
  { "url":"https://www.napkin.ai/", "title":"Napkin AI",
    "label":"napkin.ai", "cat":"Tools & Community", "sub":"miscellaneous" },
  { "url":"https://brik.space/", "title":"Brik",
    "label":"brik.space", "cat":"Tools & Community", "sub":"miscellaneous" },
  { "url":"https://chromewebstore.google.com/detail/cat-gatekeeper/elbikiflgfhjdjmficnigpeegjbhdidh", "title":"Cat Gatekeeper",
    "label":"chromewebstore.google.com/cat-gatekeeper", "cat":"Pass Time", "sub":"Cats, Poetry and Joy" },
  { "url":"https://searchingforbirds.visualcinnamon.com/", "title":"Searching for Birds",
    "label":"searchingforbirds.visualcinnamon.com", "cat":"Pass Time", "sub":"Birds, Flowers" },
  { "url":"https://shoulditbeameeting.com/#/", "title":"Should It Be a Meeting?",
    "label":"shoulditbeameeting.com", "cat":"Learn & Collaborate", "sub":"Should it be a meeting?" }
];

var CATS = [
  { "name":"Design Resources", "emoji":"\ud83c\udfa8", "subs":[
      { "name":"Personas and Journey Maps", "emoji":"\ud83e\uddd5" },
      { "name":"Icons & Symbology", "emoji":"\u2663\ufe0f" },
      { "name":"Illustrations", "emoji":"\ud83c\udf55" },
      { "name":"Glyphs and Patterns", "emoji":"\ud83d\udcb4" },
      { "name":"Logo Lab", "emoji":"\ud83d\udd2e" },
      { "name":"Boards, Charts, Mind maps", "emoji":"\ud83d\uddc2\ufe0f" },
      { "name":"Colors", "emoji":"\ud83c\udf08" },
      { "name":"Typography", "emoji":"\ud83e\udd93" },
      { "name":"Image Generation", "emoji":"\ud83e\uddda" },
      { "name":"Scales and Grids", "emoji":"\ud83d\udcd0" },
      { "name":"Mockups", "emoji":"\ud83d\udcf1" },
      { "name":"Exercise, Quizzes", "emoji":"\u2b55" },
      { "name":"3D", "emoji":"\ud83d\uddff" }
  ] },
  { "name":"Design References", "emoji":"\ud83d\udcd0", "subs":[
      { "name":"A11y and checklists", "emoji":"\u267f" },
      { "name":"Design Theory", "emoji":"\ud83d\udcd4" },
      { "name":"Interface Tips and Spells", "emoji":"\ud83e\ude84" },
      { "name":"Data Visualized", "emoji":"\ud83d\udcbf" },
      { "name":"Guides, Codes, Manifestos", "emoji":"\ud83d\udd26" },
      { "name":"UX Methods, Laws", "emoji":"\ud83d\udc19" },
      { "name":"Interface Patterns", "emoji":"\ud83d\udc41\ufe0f" },
      { "name":"UX Case studies", "emoji":"\u2705" },
      { "name":"eyecandy", "emoji":"\ud83c\udf6d" },
      { "name":"Sustainable design", "emoji":"\ud83c\udf4f" },
      { "name":"Naming Guide", "emoji":"\ud83e\uddf5" },
      { "name":"Maps", "emoji":"\ud83d\uddfa\ufe0f" }
  ] },
  { "name":"Tools & Community", "emoji":"\ud83e\uddf0", "subs":[
      { "name":"Toolkits + Method Cards", "emoji":"\ud83d\udd28" },
      { "name":"Generators", "emoji":"\ud83d\udc37" },
      { "name":"Moodboards, wormholes", "emoji":"\ud83d\udc7e" },
      { "name":"Make a game", "emoji":"\u2663\ufe0f" },
      { "name":"Cascading Style Sheets", "emoji":"\ud83c\udfc1" },
      { "name":"design communities", "emoji":"#\ufe0f\u20e3" },
      { "name":"Publish a website, blog", "emoji":"\ud83d\ude4e" },
      { "name":"local", "emoji":"\ud83d\udccd" },
      { "name":"Drawing, Scrawling", "emoji":"\u3030\ufe0f" },
      { "name":"Decks, Cards, Pages", "emoji":"\ud83d\udfe1" },
      { "name":"Notes, browsers", "emoji":"\u270d\ufe0f" },
      { "name":"Cookies", "emoji":"\ud83c\udf6a" },
      { "name":"Alternate Tools", "emoji":"\ud83d\udc0c" },
      { "name":"miscellaneous", "emoji":"\ud83c\udf4c" }
  ] },
  { "name":"Learn & Collaborate", "emoji":"\ud83e\udd1d", "subs":[
      { "name":"Sketchplanations", "emoji":"\u270f\ufe0f" },
      { "name":"Contracts, Emails", "emoji":"\ud83e\udd1d" },
      { "name":"Zero Waste Resources", "emoji":"\u267b\ufe0f" },
      { "name":"Work from anywhere", "emoji":"\ud83c\udfe1" },
      { "name":"Should it be a meeting?", "emoji":"\ud83d\ude46" },
      { "name":"Endangered", "emoji":"\ud83e\udd8f" },
      { "name":"A lesson in Art History", "emoji":"\ud83d\uddbc\ufe0f" },
      { "name":"sign language", "emoji":"\ud83e\udd1e" },
      { "name":"Cognitive Bias Index", "emoji":"\ud83e\udde0" },
      { "name":"IceBreakers", "emoji":"\u26f8\ufe0f" },
      { "name":"Timers", "emoji":"\u23f3" }
  ] },
  { "name":"Pass Time", "emoji":"\ud83c\udfb2", "subs":[
      { "name":"Mythology", "emoji":"\ud83d\udc09" },
      { "name":"Site of Sites", "emoji":"\ud83d\udc80" },
      { "name":"Sounds", "emoji":"\ud83c\udfa7" },
      { "name":"Windows, Houses, Parks", "emoji":"\ud83c\udf3f" },
      { "name":"Cats, Poetry and Joy", "emoji":"\ud83c\udf3c" },
      { "name":"Test, Taste", "emoji":"\u2696\ufe0f" },
      { "name":"TV, Radio", "emoji":"\ud83d\udcfa" },
      { "name":"typology, collections", "emoji":"\ud83c\udfb2" },
      { "name":"Books, Places to read", "emoji":"\ud83d\udcd6" },
      { "name":"Film things", "emoji":"\ud83c\udfac" },
      { "name":"Artificial Intelligence", "emoji":"\u2601\ufe0f" },
      { "name":"Birds, Flowers", "emoji":"\ud83d\udc26" },
      { "name":"Earth Typo", "emoji":"\ud83d\uddfa\ufe0f" }
  ] }
];
